version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio-app
    ports:
      # Mapping Host:8081 ke Container:8081
      - "8081:8081"
    environment:
      - VIRTUAL_HOST=aanoo.xyz
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=aanoo.xyz
      - LETSENCRYPT_EMAIL=akhmadsubkhan2212@gmail.com
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
